chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.chat, name='chat'),
    path('<username>', views.chat, name='chat'),
    path('<username>/send_chat_message/', views.send_chat_message, name='send_chat_message'),
]

report/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("new_report", views.new_report, name="new_report"),
    path("add_report", views.add_report, name="add_report"),
    path("add_sighting/<report_public_id>", views.add_sighting, name="add_sighting"),
    path("check_report", views.check_report_presence, name="check_report_presence"),
    path("create_report", views.create_report, name="create_report"),
    path("create_sighting/<report_public_id>", views.create_sighting, name="create_sighting"),
    path("view_report/<report_public_id>", views.view_report, name="view_report"),
    path("add_to_watchlist/<report_public_id>", views.add_to_watchlist, name="add_to_watchlist"),
    path("remove_from_watchlist/<report_public_id>", views.remove_from_watchlist, name="remove_from_watchlist"),
    path("hide_comment/<comment_id>", views.hide_comment, name="hide_comment"),
    path("show_comment/<comment_id>", views.show_comment, name="show_comment"),
    path("edit_report/<report_public_id>", views.edit_report, name="edit_report"),
    path("update_report/<report_public_id>", views.update_report, name="update_report"),
    path("report_evidence/<report_public_id>", views.report_evidence, name="report_evidence"),
    path("edit_sighting/<sighting_id>", views.edit_sighting, name="edit_sighting"),
    path(
        "update_sighting/<sighting_id>", views.update_sighting, name="update_sighting"
    ),
    path("my-activity", views.my_activity, name="my-activity"),
    path("my-task", views.my_task, name="my-task"),
    path("add_comment", views.add_comment, name="add_comment"),
    path("delete_comment/<comment_id>", views.delete_comment, name="delete_comment"),
    path("view_report/<report_public_id>/comments/", views.comments, name="comments"),
    path("view_report/<report_public_id>/comments/<comment_id>/flag/", views.flag_comment, name="flag_comment"),
    path("view_report/<report_public_id>/sightings/", views.sightings, name="sightings"),
    path("statistics/data", views.statistics_data, name="statistics_data"),
    path("statistics/", views.statistics, name="statistics"),
    path("statistics2/<int:id>/data", views.statistics_data2, name="statistics_data2"),
    path("statistics2/<int:id>/", views.statistics2, name="statistics2"),

]

wikirumours/urls.py
from django.contrib import admin
from django.contrib.admin import AdminSite
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.conf.urls import url

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls.i18n import i18n_patterns
from report.views import content_page
from users.views import logout_user
from users.views import handler404,handler500
from rest_framework.routers import DefaultRouter
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

router = DefaultRouter()
router.register(r'devices', FCMDeviceAuthorizedViewSet)


handler404 = handler404
handler500 = handler500

AdminSite.site_header = 'Settings'
AdminSite.site_title = 'Settings'
AdminSite.index_title = ''



schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = i18n_patterns(
    url(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    url(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    url(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    # path('api/',include('api.urls')),
    # path('', include(router.urls)),
    path("", lambda r: HttpResponseRedirect("/home")),
    path("admin/", admin.site.urls),
    url(r"^reports/", include("report.urls")),
    url(r"^chat/", include("chat.urls")),
    url(r"^articles/", include("articles.urls")),
    url(r"^api/", include("report.api_urls")),
    url(r"^newapi/", include("newapi.urls")),
    url("", include("users.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    path("content/<content_slug>", content_page, name="content_page"),

    url(r"^taggit/", include("taggit_selectize.urls")),
    path('', include(router.urls)),
    # path('api/', include('rest_framework.urls')),
)

urlpatterns += path("admin/", include('loginas.urls')),

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logs/models.py
from django.db import models
from report.models  import *


class UserLogs(models.Model):
    CHOICES = (
        ('Sign In','Sign In'),
        ('Update User Profile','Update User Profile'),
        ('Password Change','Password Change'),
        ('Create Report','Create Report'),
        ('Update Report','Update Report'),
        ('Report Evidence','Report Evidence'),
        ('Create Sighting','Create Sighting'),
        ('Update Sighting','Update Sighting'),
        ('Generate API Key','Generate API Key'),
        ('Add Comment','Add Comment'),
        ('Flag Comment','Flag Comment'),
        ('Hide Comment','Hide Comment'),
        ('Show Comment','Show Comment'),
        ('Remove Comment','Remove Comment'),
        ('Add To Watchlist','Add To  Watchlist'),
        ('Remove From Watchlist','Remove From Watchlist'),
        ('Sign Out','Sign Out')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,db_index=True)
    ip_address = models.GenericIPAddressField(null=True,blank=True)
    action = models.CharField(max_length=50,choices=CHOICES)
    report = models.ForeignKey(Report, on_delete=models.CASCADE,null=True,blank=True)
    sighting = models.ForeignKey(Sighting, on_delete=models.CASCADE,null=True,blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE,null=True,blank=True)
    evidence = models.ForeignKey(EvidenceFile, on_delete=models.CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'User Log' 
        verbose_name_plural = 'User Logs'

    def __str__(self):
        return self.user.first_name+' '+self.user.last_name+' ----- '+self.action

report/views.py
import datetime
import heapq
import json
import re
from datetime import timedelta
from heapq import heappush, nlargest
from itertools import combinations

import magic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.gis.geos import Point
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Count, Q
from django.db.models.functions import TruncDay, TruncMonth
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import ugettext_lazy
from django.views.decorators.http import require_http_methods
from geopy.geocoders import Nominatim
from rest_framework import viewsets, status
from rest_framework.authentication import SessionAuthentication
from rest_framework.decorators import action as drf_action
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response

from countries.models import Country
from users.authentication import ApiAuthentication
from users.emails import new_report_alert, emergency_report_alert
from users.models import User
from wikirumours.base_settings import GOOGLE_MAPS_KEY, MAPBOX_API_KEY
from .forms import (
    AddReportForm,
    EndUserSightingForm,
    AdminReportForm,
    CommunityLiaisonForm,
    AddSightingForm, ReportFilterForm,
)
from .models import *
from .serializers import *
from .utils import get_tags_from_title, get_location_array 
from django.contrib.sites.shortcuts import get_current_site
from django.template.context_processors import csrf
from logs.utils import *
from newapi.jwt_token_auth import get_token, decrypt_token
from rest_framework import generics, filters
from django_filters.rest_framework import DjangoFilterBackend
from django.core import serializers as se
from .send_notification import FCMPushView, add_mobile_token, delete_mobile_token, update_mobile_token
from newapi.models import LoginDetail
from fcm_django.models import FCMDevice


# Create your views here.
def index(request):
    request_domain = get_current_site(request).domain
    reports = Report.objects.annotate(count=Count("sighting"))
    domain_query = Domain.objects.filter(domain=request_domain)
    if domain_query.exists():
        domain = domain_query.first()
        if not domain.is_root_domain:
            reports = reports.filter(domain=domain)

    # filters
    search_term = request.GET.get("search_term")
    if search_term:
        reports = reports.filter(title__icontains=search_term)

    status = request.GET.get("status")
    if status:
        reports = reports.filter(status__name=status)

    priority = request.GET.get("priority")
    if priority:
        reports = reports.filter(priority__name=priority)

    country = request.GET.get("country")
    if country:
        reports = reports.filter(country__name=country)

    # sort
    sort_by = request.GET.get("sort_by")

    if sort_by == "most_sighted":
        reports = reports.annotate(count=Count("sighting")).order_by("-count")
    elif sort_by == "recently_occurred":
        reports = reports.order_by('-occurred_on')
    else:
        reports = reports.order_by('-updated_at')

    # filter form
    form = ReportFilterForm(request.GET)

    paginator = Paginator(reports, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj,
               "reports": page_obj.object_list,
               "search_term": search_term or '',
               "form": form}

    return TemplateResponse(request, "report/reports.html", context)


class StandardResultPagination(PageNumberPagination):
    page_size = 15
    page_size_query_param = "page_size"
    max_page_size = 1000


class ReportViewSet(viewsets.ModelViewSet):
    pagination_class = StandardResultPagination
    authentication_classes = (
        SessionAuthentication,
        ApiAuthentication,
    )
    queryset = Report.objects.all()
    serializer_class = ReportSerializer

    http_method_names = ["get", "post", "put"]

    @transaction.atomic
    def create(self, request, *args, **kwargs):
        username = request.headers.get("username")
        api_key = request.headers.get("Api-key")

        user = User.objects.filter(username=username, api_key=api_key).first()

        # check if user is permitted to make POST requests
        if not user.api_post_access:
            return HttpResponseForbidden("You have insufficient permissions")
        request_domain = get_current_site(request).domain
        domain_query = Domain.objects.filter(domain=request_domain)
        if domain_query.exists():
            domain = domain_query.first()
        else:
            domain = Domain.objects.all().first()
        latlong = None
        report_address = None
        locator = Nominatim(user_agent="wikirumours")
        if request.data.get("report_location"):
            location = request.data.get("report_location").split(",")
            report_latlong = "{},{}".format(location[0], location[1])

            latlong = Point(float(location[1]), float(location[0]))
            try:
                report_address = locator.reverse(report_latlong)

            except Exception:

                report_address = report_latlong

        report_country = Country.objects.filter(
            iso_code=request.data.get("country")
        ).first()

        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            report = serializer.save(
                reported_by=user,
                domain=domain,
                country=report_country,
                location=latlong,
                address=report_address,
            )
        sighting_serializer = SightingSerializer(data=request.data)
        latlong_sighting = None
        sighting_address = None
        if request.data.get("sighting_location"):
            location = request.data.get("sighting_location").split(",")
            sighting_latlong = "{},{}".format(location[0], location[1])
            latlong_sighting = Point(float(location[1]), float(location[0]))
            try:
                sighting_address = locator.reverse(sighting_latlong)
            except Exception:

                sighting_address = sighting_latlong

        sighting_country = Country.objects.filter(
            iso_code=request.data.get("sighting_country")
        ).first()
        if sighting_serializer.is_valid(raise_exception=True):
            sighting_serializer.save(
                user=user,
                report=report,
                is_first_sighting=True,
                country=sighting_country,
                location=latlong_sighting,
                address=sighting_address,
            )
        log_data = {'ip_address':get_client_ip(request),'user':user,'action':'Create Report','report':report}
        create_user_log(log_data)
        headers = self.get_success_headers(sighting_serializer.data)
        data = {"report": serializer.data}
        return Response(data, status=status.HTTP_201_CREATED, headers=headers)

    def list(self, request, *args, **kwargs):
        print("here*********")
        request_domain = get_current_site(request).domain
        domain_query = Domain.objects.filter(domain=request_domain)
        if domain_query.exists():
            domain = domain_query.first()
        else:
            domain = Domain.objects.all().first()
        queryset = Report.objects.all()

        if not domain.is_root_domain:
            queryset = queryset.filter(domain=domain)

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        report_serializer = self.get_serializer(instance)
        return Response(report_serializer.data)

    def update(self, request, *args, **kwargs):
        username = request.headers.get("username")
        api_key = request.headers.get("Api-key")

        user = User.objects.filter(username=username, api_key=api_key).first()

        # check if user is permitted to make POST requests
        if not user.api_post_access:
            return HttpResponseForbidden("You have insufficient permissions")

        partial = kwargs.pop("partial", False)
        instance = self.get_object()
        if instance.reported_by == user:
            report_country = Country.objects.filter(
                iso_code=request.data.get("country")
            ).first()
            serializer = self.get_serializer(
                instance, data=request.data, partial=partial
            )
            locator = Nominatim(user_agent="wikirumours")
            if request.data.get("report_location"):
                location = request.data.get("report_location").split(",")
                report_latlong = "{},{}".format(location[0], location[1])
                latlong = Point(float(location[1]), float(location[0]))
                try:
                    report_address = locator.reverse(report_latlong)
                except Exception:
                    report_address = report_latlong
                if serializer.is_valid(raise_exception=True):
                    report = serializer.save(
                        country=report_country, location=latlong, address=report_address
                    )
            else:

                if serializer.is_valid(raise_exception=True):

report/templates/report/add_sighting.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block extra_header%}


{{ sighting_form.media }}

{% endblock %}

{% block main_project%}
<div class="w-full">
    <div class="text-2xl md:text-4xl mt-4 font-bold  text-center text-wr-blue">
        {% trans 'Add sighting'%}
    </div>

    <div class="wr-input-container mt-8 mb-16">
        <div class="text-xl md:text-2xl text-center text-wr-grey dark:text-white px-4 mt-4 py-2">
            {{report}}
        </div>
        <form method="post" class="flex flex-col p-1 bg-wr-shadow dark:bg-wr-grey-dark rounded"
            action="{% url 'create_sighting' report_public_id=report_public_id %}" enctype="multipart/form-data" id="AddSighting">
            <div class="rounded px-8 md:px-12 py-8 md:py-12 mt-4 flex flex-col bg-wr-shadow dark:bg-wr-grey-dark">

                {%csrf_token%}
                {%for field in sighting_form %}
                <div class="text-xs md:text-md text-wr-grey dark:text-white  font-bold mb-2">{{field.label}}</div>


                {{field}}
                <div class="text-red-600 py-2 md:font-extrabold">{{field.errors}}</div>
                {% endfor %}


                <div class="flex justify-end py-4">
                    <button class="bg-blue-400 text-white font-bold py-1 md:py-2 px-4 md:px-6 rounded" type="submit">
                        Next
                    </button>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    window.onload = function () {
        jQuery('#id_sighting-heard_on').datetimepicker();
    };



</script>

{% endblock %}

report/templates/report/blogs_list.html
{% extends 'base.html'%}
{% load i18n %}
{% load static%}
{% block main_project%}
<div class="p-2">
    {% if blog_pages %}
    <div class="text-2xl md:text-3xl font-bold  text-center text-blue-500">{% trans 'Articles' %}</div>
    <br/>
    <div class="flex flex-col p-2 bg-wr-shadow dark:bg-wr-grey-dark rounded">
        {% for blog_page in blog_pages %}
            {% if forloop.counter > 1%}<hr/>{% endif %}
            <div class="text-blue-500 mt-2 md:px-2">{{blog_page.created_at|date }}</div>
            <div class="my-2 md:p-2">
                <a class="dark:text-white text-black"
                   href="{% url 'blog_page' content_slug=blog_page.content_slug %}">
                    {% trans blog_page.title %}
                </a>
            </div>
            {% if blog_page.subtitle %}
            <div class="text-base ml-2">
                {{blog_page.subtitle}}
            </div>
            {% endif %}

        {% endfor  %}
    </div>
    {% else %}
    <div class="text-center text-xl text-wr-grey dark:text-white font-medium mt-4">No articles found.</div>
    {% endif %}

</div>
{% endblock%}

report/templates/report/comment_table.html
{% load static %}
{% load i18n %}

{% if comments %}
<div class="md:justify-center bg-wr-shadow dark:bg-wr-grey-dark text-wr-grey-dark dark:text-white">
    <div class="overflow-x-auto">
        <table class="table-fixed border dark:border-white border-wr-grey w-full rounded">
            <thead class="bg-wr-grey-light dark:bg-wr-grey-dark text-center">
            <tr>
                <th class="w-1/3 wr-report-table-cell-header px-4 text-left">
                    {% trans 'Comment' %}
                </th>
                <th class="wr-report-table-cell-header">
                    {% trans 'Report' %}
                </th>
                <th class="wr-report-table-cell-header">
                    {% trans 'Date' %}
                </th>
            </tr>
            </thead>
            <tbody class="table-row-group">
            {%for comment in comments %}
            <tr class="table-row">
                <td class="w-1/3 wr-report-table-cell-row text-left">
                    <a class="cursor-pointer line-clamp-4"
                       href="{% url 'comments' report_public_id=comment.report.public_id%}">
                        {{comment.comment }}
                    </a>

                </td>
                <td class="w-1/3 wr-report-table-cell-row text-left">
                    <a class="cursor-pointer line-clamp-4"
                       href="{% url 'comments' report_public_id=comment.report.public_id%}">
                        {{comment.report }}
                    </a>

                </td>
                <td class="wr-report-table-cell-row">
                    <a class="cursor-pointer" href="{% url 'comments' report_public_id=comment.report.public_id%}">
                        {{comment.created_at}}
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="md:hidden flex justify-center items-center md:px-8 mt-8 space-x-2">
    <div class="flex mr-4 dark:text-white">
        {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}
    </div>
</div>
<div class="flex justify-center md:justify-end items-center md:px-8 mt-8 space-x-2">
    {% if page_obj.has_previous %}
    <button class="action-button-ter"><a
            href="?{{page_query}}=1{% for key, value in request.GET.items %}{% if key != page_query %}&{{ key }}={{ value }}{% endif %}{% endfor %}">First</a>
    </button>
    <button class="action-button-ter"><a
            href="?{{page_query}}={{page_obj.previous_page_number}}{% for key, value in request.GET.items %}{% if key != page_query %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Previous</a>
    </button>
    {% endif %}

    <span class="hidden md:flex mr-4 dark:text-white">
                {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}
            </span>

    {% if page_obj.has_next %}
    <button class="action-button-ter"><a
            href="?{{page_query}}={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != page_query %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Next</a>
    </button>
    <button class="action-button-ter"><a
            href="?{{page_query}}={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.items %}{% if key != page_query %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Last </a>
    </button>
    {% endif %}
</div>

{% endif %}

report/templates/report/edit_sighting.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block extra_header%}

<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src='{% static "js/jquery.cookie.min.js"%}'></script>

{{ sighting_form.media }}

{% endblock %}

{% block main_project%}
<div>
    <div class="mx-auto p-2 md:p-8 w-auto md:w-3/4">
    <div class="text-xl">{% trans 'Edit sighting for'%} <span class="text-blue-600 text-2xl px-3">{{sighting.report}}</span> </div>


        <div class="shadow-2xl rounded px-8 md:px-12 py-8 md:py-12 mt-4 flex flex-col bg-white ">
            <form method="post" action="{% url 'update_sighting'  sighting_id=sighting.id %}"
                  enctype="multipart/form-data" id="EditSighting">

                {%csrf_token%}
                {%for field in sighting_form %}
                <div class="text-xs md:text-md text-wr-grey font-bold mb-2">{{field.label}}</div>


                {{field}}
                <div class="text-red-600 py-2 md:font-extrabold">{{field.errors}}</div>
                {% endfor %}


                <div class="flex justify-end py-4">
                    <button class="bg-blue-400 text-white font-bold py-1 md:py-2 px-4 md:px-6 rounded" type="submit">

                        Next
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

report/templates/report/home.html
<html>
{% extends 'base.html' %}
{% load i18n %}

{% block main_project %}
<div class="p-8 dark:text-white dark:bg-wr-grey-dark mt-8">
    {% if request.domain and request.domain.index_cms_page %}
    {{request.domain.index_cms_page.html_content|safe}}
    {% else %}
    <div class="justify-center">
        <p class="text-md md:text-xl">
            Misinformation and disinformation pose a challenge to development, governance, public health, and human
            security efforts around the world. WikiRumours is a workflow and technology platform designed to counter the
            spread of false information through transparency and early mitigation of conflict.
        </p>
        <p class="mt-10 text-md md:text-xl  ">
            As communications technology has become more widely distributed in the developing world, the spread of
            inaccurate, incomplete or fabricated information is an increasingly significant threat to peace and
            stability, particularly in regions with limited access to reliable third-party media.
        </p>
        <p class="mt-10 text-md md:text-xl ">
            WikiRumours can be used to contextualize and mitigate misinformation through community involvement, crisis
            moderation, and transparency.
        </p>
        <div class="mb-4 text-md md:text-xl mt-8">Want to help?</div>
        <ul class="text-md md:text-xl list-disc list-inside">
            <li>If you've heard a rumour in your community which represents an immediate risk of conflict, <a
               href="{% url 'new_report' %}" class=" underline hover:underline dark:text-white text-wr-grey cursor-pointer"> report it now.</a>
            </li>
            <li>If you have verifiable information on an existing rumour recorded in WikiRumours, leave a comment on
                it.
            </li>
            <li>If you want to implement a private, local instance of WikiRumours, download the open source version of
                the software (coming soon).
            </li>
            <li>Spread the word about WikiRumours in your community and beyond!</li>
        </ul>
    </div>
    {% endif %}
</div>
{% endblock %}
</html>

report/templates/report/index.html
<html>
    {% extends 'base.html' %}
   {%load static%}


{% block main_project %}
<div class="h-full justify-center ">
    <div class="w-full mt-6  text-2xl border text-center"> This is index page of {{current_host}}</div>
    {%if default %}
   <img  src="{{ default }}" alt="Card image cap"/>
    {%else %}
    <img src ="{{domain.logo.url}}" target="_blank">{{domain.domain}}</img>
    {% endif %}
</div>
{% endblock %}
</html>

report/templates/report/my_activity.html
{% extends 'base.html' %}
{%load static%}
{% load i18n%}

{% block main_project %}
<div class="h-full w-full">
    {% if reports or sightings %}
    <div class="text-2xl md:text-4xl mt-4 font-bold  text-center text-wr-blue">{% trans 'My Activity' %}</div>
    {% endif %}
    {% if watchlisted_reports %}
    <div class="text-xl md:text-2xl dark:text-white text-wr-grey px-4 mt-4 py-2">{% trans 'Watchlisted reports' %}
    </div>
    <div class="md:mx-auto p-2 md:p-4 mt-4">
        {% with reports=watchlisted_reports page_obj=watchlisted_reports_page_obj page_query="watchlisted_page"%}
        {% include 'report/report_table.html' %}
        {% endwith %}
    </div>
    {% endif %}

    {% if reports %}
    <div class="text-xl md:text-2xl dark:text-white text-wr-grey px-4 mt-4 py-2">{% trans 'Reports added by you' %}
    </div>
    <div class="md:mx-auto p-2 md:p-4 mt-4">
        {% with reports=reports page_obj=reports_page_obj page_query="reports_page" %}
        {% include 'report/report_table.html' %}
        {% endwith %}
    </div>
    {% endif %}

    {% if sightings %}
    <div class="text-xl md:text-2xl text-wr-grey dark:text-white px-4 mt-12 py-2">
        {% trans 'Sightings added by you' %}
    </div>

    <div class="md:mx-auto p-2 md:p-4 mt-4 mb-8">
        {% with sightings=sightings page_obj=sightings_page_obj page_query="sightings_page"%}
        {% include 'report/report_sighting_table.html' %}
        {% endwith %}
    </div>
    {% endif %}

    {% if not reports and not sightings %}
    <div class="text-center text-xl text-wr-grey dark:text-white font-medium mt-4">
        {% trans 'No matching activity' %}
    </div>
    {% endif %}

</div>
{% endblock %}

report/templates/report/new_report.html
{% extends 'base.html' %}
{% load static %}
{% load i18n%}

{% block main_project%}
<div class="h-full w-full">
    <div class="text-2xl md:text-4xl mt-4 font-bold  text-center text-wr-blue">
        {% trans 'Add a new Report' %}
    </div>

    <div class="md:mx-auto p-2 md:p-4 mt-4">
        <form class="flex flex-col p-1 bg-wr-shadow dark:bg-wr-grey-dark rounded"
              method="post" action="{% url 'check_report_presence'%}">
            {% csrf_token %}
            <div class="w-full md:w-full wr-shadow p-2 flex rounded">
                <input type="text"
                       class="flex-1 rounded pl-2 dark:text-white dark:bg-wr-grey form-control text-wr-grey"
                       name="title"
                       id="title" placeholder="{% trans 'Enter title of report' %}"/>
                <button class="action-button ml-4" type="submit">
                    {% trans 'Add Report' %}
                </button>
            </div>
        </form>
        {% if error %}
        <div class="flex flex-col mx-auto px-3 w-auto text-xl text-red-800 font-medium mt-4">
            <span class="text-sm text-red-600">{{error}}</span>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

report/templates/report/report_evidence.html
{% extends 'base.html' %}
{% load i18n %}
{% load static%}
{% block extra_header%}

{% endblock %}

{% block main_project %}
<div class="w-full text-center">
        {% for message in messages %}
        <div>
            <li class=" text-red-600 py-2 font-extrabold" > {{ message }}</li>
        </div>
        {% endfor %}
        <div class="wr-input-container">
            <div class="text-xl md:text-4xl text-center font-bold  mt-4  text-wr-blue mb-8"> {% trans 'Upload Evidence' %}</div>
            <div class="text-lg my-4">For report : {{report}}</div>
            <div class="blue-links">
            {% for evidence_file in report.evidencefile_set.all %}
            <div>
                <a href="{{evidence_file.file.url}}">
                    {{evidence_file.filename}}
                </a>
            </div>
            {% endfor %}
            </div>
            <div class="mt-4">
                Note: Only files which are made public by an admin will appear on the report page.
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mt-5"><input type="file" name="evidence_files" multiple></div>
                <div class="mt-5"><button class="action-button" type="submit">Upload</button></div>
            </form>
        </div>
</div>
{% endblock %}